[supervisord]
nodaemon=true
user=appuser
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[group:worker]
programs=queue-worker,scheduler
priority=10

[program:queue-worker]
process_name=%(program_name)s
command=php /app/artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600 --timeout=60 --max-jobs=250 --memory=96
autostart=true
autorestart=true
startsecs=3
priority=10
user=appuser
redirect_stderr=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=3600

[program:scheduler]
process_name=%(program_name)s
command=php /app/artisan schedule:work
autostart=true
autorestart=true
startsecs=3
priority=5
user=appuser
redirect_stderr=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
